// react-component-comm/src/body.js
import React, { Component } from 'react';
import { render } from 'react-dom';

export class Body extends Component {
  constructor(props) {
    super(props);
  }

  render(props) {
    const {page} = this.props;
    let element = <h5>Welcome to demo. Select menu.</h5>;
    if(page){
      element  = <span> You are in {page} page.</span>;
    }
    return (
      <section className="container pt-2">
        {element}
      </section>
    )
  }
}

// angular-component-com/src/app/body.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-body',
  template: 
  `
    <section class="container pt-2">
      <div *ngIf='page;else info'>
        You are in {{page}} page
      </div>
      <ng-template #info>
        <h5>Welcome to demo. Select menu.</h5>
      </ng-template>
    </section>
  `
})
export class BodyComponent  {
  @Input() page;
}
